### ISSUE TITLE
Define environment variables

### ISSUE THREAD

**Issue by EastAPOLO** [Ckath/fuf#29]
In fuf.c you get the value of environment variables several times by calling getenv. I think it would look more readable if they were defined as constants so you do not have to keep typing the function.

I can send this https://github.com/EastAPOLO/fuf/commit/0090fced59a67e127988d253cc54153739d9ac97  as a pull request if you want.

**Comment by Ckath** [comment]
theres a couple things I have against this:

1. `LS_COLORS` is checked once on init() only, not afterwords, `SHELL` kinda makes sense in my mind to be able to change runtime
2. what you're doing is just defining getenv calls, you're not storing the values. what you're doing is actually calling getenv way more than I do.

**Comment by Ckath** [comment]
not really seeing the point in making a define just because I do a function call multiple times, theres far more that I do exactly the same in multiple places. it really doesnt aid readability as it was already clear what I was doing
